const PptxGenJS = require("pptxgenjs");

class PPTXService {
  /**
   * Converts a Tiptap Document JSON into a PowerPoint (.pptx) presentation.
   * Returns a Buffer containing the generated PPTX file.
   */
  async generatePresentation(docContent, reportTitle = "Report Presentation") {
    const pptx = new PptxGenJS();

    // Define Presentation Layout & Theme Colors
    pptx.layout = "LAYOUT_16x9";
    pptx.title = reportTitle;
    pptx.author = "Report Hub AI";

    const PRIMARY_COLOR = "1E293B"; // Dark Slate
    const ACCENT_COLOR = "0284C7";  // Sky Blue
    const BG_COLOR = "F8FAFC";      // Soft Grey
    const TEXT_MUTED = "64748B";

    // 1. Title Slide
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: "0F172A" }; // Dark background for title

    titleSlide.addText(reportTitle.toUpperCase(), {
      x: 0.8,
      y: 2.2,
      w: 8.4,
      h: 1.5,
      fontSize: 36,
      bold: true,
      color: "FFFFFF",
      fontFace: "Arial",
      align: "left",
    });

    titleSlide.addText("Generated by Report Hub AI • Presentation Deck", {
      x: 0.8,
      y: 3.8,
      w: 8.4,
      h: 0.5,
      fontSize: 16,
      color: "38BDF8",
      fontFace: "Arial",
      align: "left",
    });

    if (!docContent || !Array.isArray(docContent.content)) {
      // Add a fallback content slide if empty
      const slide = pptx.addSlide();
      slide.addText("Overview", { x: 0.8, y: 0.6, fontSize: 24, bold: true, color: PRIMARY_COLOR });
      slide.addText("No detailed content found in report JSON.", { x: 0.8, y: 1.5, fontSize: 16, color: TEXT_MUTED });
      return await pptx.write("nodebuffer");
    }

    let currentSlide = null;
    let currentBulletPoints = [];
    let slideCount = 0;

    const createNewSlide = (titleText) => {
      const slide = pptx.addSlide();
      slide.background = { color: BG_COLOR };

      // Header Banner
      slide.addText(titleText || "Report Summary", {
        x: 0.8,
        y: 0.5,
        w: 8.4,
        h: 0.8,
        fontSize: 24,
        bold: true,
        color: PRIMARY_COLOR,
        fontFace: "Arial",
      });

      // Accent Underline Bar
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 1.3,
        w: 1.5,
        h: 0.06,
        fill: { color: ACCENT_COLOR },
      });

      slideCount++;
      return slide;
    };

    // Traverse Tiptap Node Structure
    for (const node of docContent.content) {
      if (node.type === "heading") {
        const headingText = this.extractText(node) || "Section";
        
        // If there were bullet points collected for previous slide, flush them first
        if (currentSlide && currentBulletPoints.length > 0) {
          this.addBulletsToSlide(currentSlide, currentBulletPoints);
          currentBulletPoints = [];
        }

        currentSlide = createNewSlide(headingText);
      } else if (node.type === "paragraph") {
        const text = this.extractText(node);
        if (!text) continue;

        if (!currentSlide) {
          currentSlide = createNewSlide(reportTitle);
        }

        // Add paragraph block or text box
        if (currentBulletPoints.length < 5) {
          currentBulletPoints.push(text);
        } else {
          // Slide is full, flush bullet points and start new slide
          this.addBulletsToSlide(currentSlide, currentBulletPoints);
          currentBulletPoints = [text];
          currentSlide = createNewSlide(reportTitle + " (Contd.)");
        }
      } else if (node.type === "bulletList" || node.type === "orderedList") {
        if (!currentSlide) {
          currentSlide = createNewSlide("Key Highlights");
        }

        if (Array.isArray(node.content)) {
          node.content.forEach((listItem) => {
            const itemText = this.extractText(listItem);
            if (itemText) currentBulletPoints.push(itemText);
          });
        }
      }
    }

    // Flush any remaining bullet points
    if (currentSlide && currentBulletPoints.length > 0) {
      this.addBulletsToSlide(currentSlide, currentBulletPoints);
    }

    // Return PPTX binary nodebuffer
    const buffer = await pptx.write("nodebuffer");
    return buffer;
  }

  addBulletsToSlide(slide, bulletTexts) {
    const formattedTexts = bulletTexts.map((text) => ({
      text: text,
      options: {
        fontSize: 16,
        color: "334155",
        bullet: { code: "2022" },
        spaceAfter: 12,
        fontFace: "Arial",
      },
    }));

    slide.addText(formattedTexts, {
      x: 0.8,
      y: 1.8,
      w: 8.4,
      h: 4.5,
      align: "left",
      valign: "top",
    });
  }

  extractText(node) {
    if (!node) return "";
    if (node.text) return node.text;
    if (Array.isArray(node.content)) {
      return node.content.map((child) => this.extractText(child)).join(" ");
    }
    return "";
  }
}

module.exports = new PPTXService();
